#######################################
#
#       ETN-1040 - v1.0
#
#######################################

networks:
  network-etn:
    name: network-etn
    driver: bridge

services:
  etn-postgres:
    container_name: etn-postgres
    image: postgres:16
    restart: always
    ports:
     - "5432:5432"
    environment:
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_URL: ${POSTGRES_URL}
      TZ: ${TZ}
    volumes:
      - ~/Desktop/etn/postgres/data:/var/lib/postgresql/data
      - ./create.sql:/docker-entrypoint-initdb.d/create.sql
      - ./insert_picture.sql:/docker-entrypoint-initdb.d/insert_picture.sql
      - ./insert.sql:/docker-entrypoint-initdb.d/insert.sql
    networks:
      - network-etn
    

  etn-backend:
    container_name: etn-backend
    image: thealanmc/etn-backend:0.9.0
    restart: always
    user: root
    ports:
      - "8080:8080"
    environment:
      PORT: ${BACKEND_PORT}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_URL: ${POSTGRES_URL}
      JWT_ISSUER: ${JWT_ISSUER}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      EMAIL_USERNAME: ${EMAIL_USERNAME}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      TZ: ${TZ}
    volumes:
      - ~/Desktop/etn/backend/logs:/opt/etn/logs/backend
    depends_on:
      - etn-postgres
    networks:
      - network-etn
      
      
  etn-frontend:
    container_name: etn-frontend
    image: thealanmc/etn-frontend:0.9.0
    user: root
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      TZ: ${TZ}
    volumes:
      - ~/Desktop/etn/frontend/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./cert.pem:/etc/nginx/cert.crt
      - ./key.pem:/etc/nginx/private.key
    depends_on:
      - etn-backend
    networks:
      - network-etn

